mrc-2528 Complete ShinyRob prototype
mrc-ide/hint-generic-chart-prototypes pull request #1
Opened 2021-07-21 11:02 UTC by EmmaLRussell

This branch fixes some of the issues remaining in the prototype at the end of the last sprint:
- fixes bug where first two subplots shared axes (need to get axis names rights, and also don't show more plots than you have defined in rows and columns settings)
- Colours line segments exceeding threshold value drop or rise in red, all other segments are black.

2021-07-22 15:51 UTC, EmmaLRussell commented on src/components/ChartSlot.vue
> +    .annotation-text {
Plotly doesn't really provide a nice way to change font weight on annotations in config, so doing it through css here, though it should really be part of the chart configuration

2021-07-27 08:35 UTC, mwoodbri approved these changes
This is really impressive - I had my doubts over whether it would even be possible to implement this chart using Plotly - especially the gradients - but it looks great and I think the performance is acceptable given the complexity of the plot (+ spinner and possibly further optimisations).

I know you mentioned it, but I think we will need a short/updated summary of how the pieces fit together, and maybe a couple of bullet points explaining the most abstruse Jsonata syntax used (`&$` etc).

2021-07-27 08:44 UTC, EmmaLRussell commented
> I know you mentioned it, but I think we will need a short/updated summary of how the pieces fit together, and maybe a couple of bullet points explaining the most abstruse Jsonata syntax used (`&$` etc).

Yes, I'll do that shortly, and great idea to also explain the Jsonata, not least as I'll definitely have forgotten how all that works before too long!

2021-07-27 09:29 UTC, Nicolas-Dolan commented
This is very nice and seems very responsive. I gather from above that not showing axis labels and chart headers is intentional at this stage? I prefer to be able to read charts at a glance without having to interact with them individually to see what they are showing. Not something that needs to be worried about in this ticket though.

2021-07-27 09:31 UTC, Nicolas-Dolan approved these changes

2021-07-27 09:36 UTC, carbowizzy requested changes
Brilliant work !

The chart is looking great. However, the only thing I can pick up is its responsiveness, I think it should be responsive. If screen is reduced then users have to scroll right to see all columns, this should automatically display 1 column when screen becomes too small to display 3 chart columns.

2021-07-27 09:39 UTC, EmmaLRussell commented
> This is very nice and seems very responsive. I gather from above that not showing axis labels and chart headers is intentional at this stage? I prefer to be able to read charts at a glance without having to interact with them individually to see what they are showing. Not something that needs to be worried about in this ticket though.

I think showing axis labels on every subplot would just take up too much real estate, user should understand meaning from context. Each subplot should now have its own header, showing area name and id - were you not seeing that?

2021-07-27 09:47 UTC, EmmaLRussell commented
> The chart is looking great. However, the only thing I can pick up is its responsiveness, I think it should be responsive. If screen is reduced then users have to scroll right to see all columns, this should automatically display 1 column when screen becomes too small to display 3 chart columns.

That would indeed be nice - Plotly won't help us with that at all I don't think sadly. 
There's a couple of use cases here:
1. Responding to width changes by redrawing plots with configured number of columns to take up new available width
2. Configuring 'minimum chart width' and using that to override configured number of columns as you describe.

I'm actually not sure what the preferred use case here is - Rachel mentioned wanting to keep default area ordering so that the users had a fixed layout from ShinyRob and could always expect to see the same area in the same position - so it might actually be preferable to scroll as currently when space is limited. I will check!

2021-07-28 09:51 UTC, EmmaLRussell commented
I've put in some basic responsiveness in the Plotly layout so that it at least responds to changes in width of the parent (albeit slowly!) Unfortunately this means that at narrow widths the titles overflow - not clear how to fix this in Plotly. I've created a ticket to deal with this in the app when requirements are clarified: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2538
Would be good to get this branch merged if you're happy to leave the prototype at that.

2021-07-28 17:34 UTC, carbowizzy approved these changes

2021-07-28 17:36 UTC, carbowizzy commented
> I've put in some basic responsiveness in the Plotly layout so that it at least responds to changes in width of the parent by resizing the plots (albeit slowly!) Unfortunately this means that at narrow widths the titles overflow - not clear how to fix this in Plotly. I've created a ticket to deal with this in the app when requirements are clarified: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2538
> Would be good to get this branch merged if you're happy to leave the prototype at that.



> I've put in some basic responsiveness in the Plotly layout so that it at least responds to changes in width of the parent by resizing the plots (albeit slowly!) Unfortunately this means that at narrow widths the titles overflow - not clear how to fix this in Plotly. I've created a ticket to deal with this in the app when requirements are clarified: https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2538
> Would be good to get this branch merged if you're happy to leave the prototype at that.

Yeah I reckon mrc-2538 will address the responsiveness further. Thank you for making some changes.

2021-07-28 17:36 UTC, merged